# Generated by Django 5.0.1 on 2025-09-24 14:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cliente_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(choices=[('CC', 'Citizenship Card'), ('CE', 'Foreign ID'), ('TI', 'Identity Card'), ('PP', 'Passport')], help_text='Document type', max_length=2)),
                ('num_doc', models.CharField(help_text='Document number', max_length=20)),
                ('nombre', models.CharField(help_text='Full client name', max_length=100)),
                ('ciudad', models.CharField(blank=True, help_text='Residence city', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'core.clientes',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credito_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(choices=[('e-bike', 'E-Bike'), ('e-moped', 'E-Moped')], help_text='Financed product type', max_length=20)),
                ('inversion', models.DecimalField(decimal_places=2, help_text='Total credit value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100000'))])),
                ('cuotas_totales', models.PositiveIntegerField(help_text='Total number of installments', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('tea', models.DecimalField(decimal_places=6, help_text='Annual effective rate', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('fecha_desembolso', models.DateField(help_text='Credit disbursement date')),
                ('fecha_inicio_pago', models.DateField(help_text='Payment schedule start date')),
                ('estado', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('written_off', 'Written Off')], default='vigente', help_text='Current credit status', max_length=20)),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'db_table': 'core.creditos',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pago_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(help_text='Payment date and time')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('medio', models.CharField(blank=True, choices=[('app', 'Mobile App'), ('cash', 'Cash'), ('link', 'Payment Link'), ('transfer', 'Transfer'), ('card', 'Card')], help_text='Payment method used', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'core.pagos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='credito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='schedule',
        ),
        migrations.AlterModelOptions(
            name='paymentschedule',
            options={'verbose_name': 'Payment Schedule', 'verbose_name_plural': 'Payment Schedules'},
        ),
        migrations.RemoveIndex(
            model_name='paymentschedule',
            name='core.paymen_credito_07dd53_idx',
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pendiente', help_text='Current installment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Installment due date'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='num_cuota',
            field=models.PositiveIntegerField(help_text='Installment number'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, help_text='Amount to pay in this installment', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tipo_doc', 'num_doc')},
        ),
        migrations.AddField(
            model_name='credit',
            name='cliente',
            field=models.ForeignKey(help_text='Credit owner client', on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.client'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='credito',
            field=models.ForeignKey(help_text='Credit this installment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='core.credit'),
        ),
        migrations.AddField(
            model_name='payment',
            name='schedule',
            field=models.ForeignKey(help_text='Installment this payment corresponds to', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.paymentschedule'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Credito',
        ),
    ]
